### ISSUE TITLE
Plugin is not adding project name so urls are incorrect

### ISSUE THREAD

**Issue by stoune** [JetBrains/TeamCity.VsOnline.WorkItems#2]
Versions: TeamCity Professional 9.1 (build 36973) 
TeamCity.VsOnline   9.1.3 
I've setup connection to VSOnline, entered test issue number and successfully get issue title(tested connection).

Now when I follow the links formed by plugin(changes tab) I see that plugin is not adding project name so links are incorrect.
Links are formed in the form:
https://account.visualstudio.com/_workitems/edit/7278
but should be:
https://account.visualstudio.com/DefaultCollection/project/_workitems/edit/7278
notice that DefaultCollection/project part if omitted.

**Comment by spinico** [comment]
Same issue here...

**Comment by demyte** [comment]
I am having the same issue as this.

Any chance for a fix @orybak? 

I am not a Java guy so unfortunately I doubt I could work out what to do to fix it and make a pull request, sorry.

**Comment by HenrikPoulsen** [comment]
Same problem here. Not much activity on fixing this one it seems.

**Comment by HenrikPoulsen** [comment]
For the sake of clarity, this has been fixed in the 9.1.x version of the plugin, so this issue can probably be closed now then.
